package audioPlayer;

import java.net.URL;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/* A wav music file that generated by a specific file path
 *  
 */
public class Music implements AudioPlayer{
	private String filepath;
	private Clip clip;
	public Music(String filePath){
		this.filepath= filePath;
	}
	@Override
	public void play() {
		URL target;
		try {
			clip = AudioSystem.getClip();
			target = new URL("file:"+this.filepath);
			AudioInputStream audioStream = AudioSystem.getAudioInputStream(target);
			clip.open(audioStream);
			clip.start();
		} catch (Exception filenotfound) {
			filenotfound.getStackTrace();
		}
	}
	
	
	public boolean isPlaying(){
		return clip.isRunning();
	}
	
	@Override
	public void pause() {
		// TODO Auto-generated method stub
		
	}
	
	
	@Override
	public void stop() {
		// TODO Auto-generated method stub
		
	}

}
